[project]
name = "catacombs-of-time"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "pygame-ce>=2.5.5",
    "pygbase-engine",
    "typing-extensions"
]

[tool.uv.sources]
pygbase-engine = { path = "../pygbase", editable = true }
